# frozen_string_literal: true

# This file was generated by the `rails generate rspec:install` command.
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

# Code coverage (must be at the top)
require "simplecov"
SimpleCov.start "rails" do
  add_filter "/spec/"
  add_filter "/config/"
  add_filter "/vendor/"

  add_group "Models", "app/models"
  add_group "Controllers", "app/controllers"
  add_group "Services", "app/services"
  add_group "Jobs", "app/jobs"
  add_group "Mailers", "app/mailers"
  add_group "Serializers", "app/blueprints"

  minimum_coverage 80
  minimum_coverage_by_file 50
end

RSpec.configure do |config|
  # rspec-expectations config
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Focus filter - run only focused specs with :focus tag
  config.filter_run_when_matching :focus

  # Persist spec results for --only-failures and --next-failure
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Disable monkey patching
  config.disable_monkey_patching!

  # Use documentation formatter for single file runs
  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  # Profile slow specs
  config.profile_examples = 10

  # Random order
  config.order = :random
  Kernel.srand config.seed
end
